FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

# Install Watchman, a file watching service
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends watchman

# Install React Native CLI
RUN npm install -g react-native-cli

# [Optional] Install additional global npm packages
# RUN su node -c "npm install -g <your-global-npm-packages-here>"

# [Optional] Install Android development tools
# Note: You might need to customize this section further based on your Android development needs
# RUN wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip \
#     && unzip android-sdk.zip -d /usr/local/android-sdk \
#     && rm android-sdk.zip \
#     && yes | /usr/local/android-sdk/tools/bin/sdkmanager --licenses \
#     && /usr/local/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
